#!/bin/bash -l

source activate torch3


python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.5 --model="Net" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test1.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.5 --model="Net" --oversample "random" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test2.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.5 --model="Net" --oversample "smote" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test3.txt

python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.5 --model="deepNet" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test4.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.5 --model="deepNet" --oversample "random" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test5.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.5 --model="deepNet" --oversample "smote" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test6.txt


python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.6 --model="Net" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test7.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.6 --model="Net" --oversample "random" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test8.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.6 --model="Net" --oversample "smote" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test9.txt

python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.6 --model="deepNet" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test10.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.6 --model="deepNet" --oversample "random" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test11.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.6 --model="deepNet" --oversample "smote" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test12.txt


python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.7 --model="Net" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test13.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.7 --model="Net" --oversample "random" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test14.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.7 --model="Net" --oversample "smote" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test15.txt

python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.7 --model="deepNet" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test16.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.7 --model="deepNet" --oversample "random" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test17.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.7 --model="deepNet" --oversample "smote" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test18.txt


python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.8 --model="Net" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test19.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.8 --model="Net" --oversample "random" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test20.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.8 --model="Net" --oversample "smote" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test21.txt

python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.8 --model="deepNet" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test22.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.8 --model="deepNet" --oversample "random" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test23.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.8 --model="deepNet" --oversample "smote" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test24.txt

python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.9 --model="Net" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test25.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.9 --model="Net" --oversample "random" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test26.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.9 --model="Net" --oversample "smote" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test27.txt

python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.9 --model="deepNet" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test28.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.9 --model="deepNet" --oversample "random" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test29.txt
python train.py --epochs=300 --batch_sz=500 --lr=1e-3  --p=0.9 --model="deepNet" --oversample "smote" --data "/u/eag-d1/scratch/derek/ma721_hw1/data/kinases_80_20.h5" --feats "/u/eag-d1/scratch/derek/ma721_hw1/data/full_kinase_set_features_list.csv" --null "/u/eag-d1/scratch/derek/ma721_hw1/data/more_than_5_percent_missing_features_list.csv" >> results/test30.txt

